---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4874/workspace/MavenAnsi/target/MavenAnsi.war"
        dest: "/opt/tomcat/webapps/MavenAnsi.war"
        remote_src: no

    - name: Restart Tomcat 
      shell: "/opt/tomcat/bin/shutdown.sh&&/opt/tomcat/bin/startup.sh"
      args:
       executable: /bin/bash
        
